name: dart_irc_bot
version: 0.1.0
description: A simple console application.
dependencies:
  http: ^0.12.0+1
  cleverbot: ^0.2.1
  xml: ^3.2.5
  markov_dart: ^0.2.0
  googleapis: ^0.52.0+1
  googleapis_auth: ^0.2.6
  fortune: ^0.1.0
  darksky_weather: ^1.1.0